<? if (@$_POST["do"] == "create" && !$form->is_form_error()): ?>
	<script type="text/javascript">
	opener.location.href = '<?= url_for("action", "explorer", "root_path", $root_path, "path", $current_folder) ?>';
	window.close();
	</script>
<? else: ?>
	<table class="wide"><tr><td style="text-align: center;"><div style="padding: 5px;">
	<form method="post">
		<input type="hidden" name="do" value="create">
		Имя: <input id="folder_name" type="text" name="name" style="width: 120px;"><input type="submit" value="Создать"><err>
	</form>
	</div></td></tr></table>
	<script type="text/javascript">
	$('folder_name').focus();
	</script>
<? endif ?>
