<script type="text/javascript">
var uploader_wait_timer = null;
function uploader_wait()
{
	uploader_wait_clear();
	var elem = $('element_submit');
	var current_step = 0;
	var wait_animation = function()
	{
		current_step++;
		if (current_step > 3) { current_step = 1; }
		var button_name = 'Идёт загрузка, ждите';
		for (var i = 0; i < current_step; i++) { button_name += '.'; }
		elem.value = button_name;
		uploader_wait_timer = setTimeout(wait_animation, 300);
	}
	wait_animation();
}

function uploader_wait_clear()
{
	if (uploader_wait_timer)
	{
		clearTimeout(uploader_wait_timer);
		uploader_wait_timer = null;
	}
}

function uploader_ready()
{
	var elem = $('element_submit');
	uploader_wait_clear();
	elem.value = 'Отправить на сервер';
}

function uploader_submit()
{
	try
	{
		$('element_path').value = parent.frames['frame_explorer'].current_folder;
		var elem_file = $('element_file');
		if (elem_file.value == '')
		{
			alert('Сначала выберите файл!');
			if (elem_file.click) { elem_file.click(); }
			return false;
		}
		else
		{
			uploader_wait();
			return true;
		}
		return true;
	}
	catch (e) { alert('Неизвестная ошибка!'); }
	return false;
}
</script>

<div class="wtitle"><div>Закачать файлы (вы можете закачать сразу несколько файлов если ваш браузер это поддерживает)</div></div>

<form action="<?= url_for("action", "upload-file", "root_path", $root_path) ?>" method="post" enctype="multipart/form-data" target="uploader_processor" onsubmit="return uploader_submit();">
<input id="element_path" type="hidden" name="parent_folder" value="">
<div style="padding: 2px;">
<table>
	<tr>
		<td><input id="element_file" type="file" name="file[]" multiple="multiple" style="width: 400px;"></td>
		<td><input id="element_submit" type="submit" value="Отправить на сервер"></td>
		<td><input type="checkbox" name="is_overwrite" value="1" id="chk_is_overwrite"><label for="chk_is_overwrite">Заменить существующий</label></td>
	</tr>
</table>
</div>
</form>

<iframe name="uploader_processor" style="width: 0px; height: 0px; position: absolute; left: 0px; top: 0px; border: 0px;" src="<?= url_for(CMS_PUBLIC_URI . "/empty.php") ?>"></iframe>
