<? if (!is_empty($error_message)): ?>
	alert('<?= j($error_message) ?>');
<? else: ?>
	var nodes = [];
	var load_node_childs = [];
	<? foreach ($affected_nodes as $item_id): ?>
		nodes.push('<?= h($item_id) ?>');
		load_node_childs.push('<?= h($item_id) ?>');
	<? endforeach ?>
	expand_tree(nodes, { 'load_node_childs': load_node_childs, 'node_inclusive': true });
	if (parent.frames['frame_func']) { parent.frames['frame_func'].location.href = '<?= url_for(CMS_PUBLIC_URI . "/empty.php") ?>'; }
<? endif ?>