<? $latest_type = null ?>
<? foreach ($nodes as $item): ?>
	<? if ($is_many_types): ?>
		<? if ($latest_type === null || $latest_type != $item["type"]): ?>
			<table>
				<tr>
					<td><img src="<?= CMS_PUBLIC_URI ?>/pics/spacer.gif" width="<?= h($item["level"] * 16 + 1) ?>" height="16" border="0" alt=""></td>
					<td onmouseup="clicked_on_node_type('<?= h($item["parent_id"]) ?>', '<?= hj($item["type"]) ?>', event);" onmouseover="this.style.color = '#ff0000';" onmouseout="this.style.color = '';" style="cursor: default; white-space: nowrap;"><b><?= h($item["type_name_list"]) ?></b></td>
				</tr>
			</table>
			<? $latest_type = $item["type"] ?>
		<? endif ?>
	<? endif ?>
	<table class="tree_item">
		<tr valign="top">
			<td><img src="<?= CMS_PUBLIC_URI ?>/pics/spacer.gif" width="<?= h($item["level"] * 16 + 1) ?>" height="16" border="0" alt=""></td>
			<? if ($item["child_count"]): ?>
				<td><img onclick="expand_or_collapse_node('<?= j($item["id"]) ?>', '<?= j($item["level"] + 1) ?>');" id="node_plus_minus_img_<?= h($item["id"]) ?>" src="<?= CMS_PUBLIC_URI ?>/pics/p.gif" width="16" height="16" border="0" alt=""></td>
			<? else: ?>
				<td><img src="<?= CMS_PUBLIC_URI ?>/pics/spacer.gif" width="16" height="16" border="0" alt=""></td>
			<? endif ?>
			<td id="node_icon_<?= h($item["id"]) ?>" onmouseup="clicked_on_node('<?= h($item["id"]) ?>', event);" ondblclick="double_clicked_on_node('<?= h($item["id"]) ?>');"><img src="<?= CMS_PUBLIC_URI ?>/pics/<?= h($item["icon"]) ?>" width="16" height="16" border="0" alt=""></td>
			<td id="node_content_<?= h($item["id"]) ?>" onmouseup="clicked_on_node('<?= h($item["id"]) ?>', event);" ondblclick="double_clicked_on_node('<?= h($item["id"]) ?>');" onmouseover="this.style.color = '#ff0000';" onmouseout="this.style.color = '';" class="not_selected" style="cursor: default; white-space: nowrap">
				<span id="node_name_<?= h($item["id"]) ?>" node_type="<?= h($item["type"]) ?>"><?= h($item["name"])?></span>
			</td>
		</tr>
	</table>
	<? if ($item["child_count"]): ?>
		<div style="display: none;" id="node_childs_<?= h($item["id"]) ?>"></div>
	<? endif ?>
<? endforeach ?>
<script type="text/javascript">
if (!click_on_load_is_done && cookie_opened_roots[root_window_url])
{
	if ($('node_name_' + cookie_opened_roots[root_window_url]))
	{
		clicked_on_node(cookie_opened_roots[root_window_url]);
		click_on_load_is_done = true;
	}
}
process_queue();
</script>
