<div class="wtitle"><div><? if (action() == "langs-add"): ?>Создание языка<? else: ?>Редактирование языка<? endif ?></div></div>

<div style="padding: 2px;">

<form method="post">
<input type="hidden" name="do" value="save">

<table>
<tr>
	<td style="text-align: right;">Код:</td>
	<td><input type="text" name="lang" style="width: 20px;"><err></td>
</tr>
<tr>
	<td style="text-align: right;">Название:</td>
	<td><input type="text" name="name" style="width: 200px;"><err></td>
</tr>
<tr>
	<td></td>
	<td><input type="checkbox" name="is_default">Основной<err></td>
</tr>
<? if (action() == "langs-add"): ?>
	<tr>
		<td style="text-align: right;">Скопировать данные из:</td>
		<td>
			<select name="copy_from">
			<option value="">---</option>
			<? foreach (cms_get_all_languages() as $lang): ?>
				<option value="<?= h($lang["lang"]) ?>"><?= h($lang["name"]) ?></option>
			<? endforeach ?>
			</select><err>
		</td>
	</tr>
<? endif ?>
<tr>
	<td></td>
	<td><input type="submit" value="Сохранить"></td>
</tr>
</table>
</form>

</div>