<div class="wtitle"><div>Выполнение SQL запроса</div></div>

<div style="padding: 2px;">

<form method="post">
<input type="hidden" name="do" value="run">

<table style="width: 100%;"><tr><td>
<div style="margin-right: 6px;">
	<textarea style="width: 100%; height: 200px;" name="sql" wrap="off"></textarea>
	<? if ($form->is_error("sql")): ?><div style="color: #ff0000;"><?= hm($form->get_error_text("sql")) ?></div><? endif ?>
</div>
</td></tr></table>

<table><tr>
<td><input type="submit" value="Выполнить"></td>
<td style="padding-left: 5px;">
<? if (@$_POST["do"] == "run" && !$form->is_form_error()): ?>
	<b>Затронуто рядов в последней инструкции:</b> <?= h(db_affected_rows($result)) ?>,
	<b>Время выполнения:</b> <?= h($query_time) ?>
<? endif ?>
</td>
</tr></table>

<? if (@$_POST["do"] == "run" && !$form->is_form_error()): ?>
	<? if (db_num_rows($result)): ?>
		<table class="list">
		<? $i = 0 ?>
		<? while (false !== $row = db_fetch($result)): ?>
			<? if (!$i): ?>
				<tr>
					<? foreach ($row as $name => $value): ?>
						<th><?= h($name) ?></th>
					<? endforeach ?>
				</tr>
			<? endif ?>
			<tr>
				<? foreach ($row as $value): ?>
					<td><?= $value === null ? "<b>[NULL]</b>" : (!is_empty($value) ? hm($value) : "&nbsp;") ?></td>
				<? endforeach ?>
			</tr>
			<? $i++ ?>
		<? endwhile ?>
		</table>
	<? endif ?>
<? endif ?>

</form>

</div>