<? include_view("_submenu") ?>

<div class="wtitle"><div>Потомки типа</div></div>

<div style="padding: 2px;">

<form method="post">
<input type="hidden" name="do" value="save">
<table>
	<tr>
		<td style="vertical-align: top; white-space: nowrap;">
		<? $n = 0; $count = count($types) ?>
		<? foreach ($types as $item): ?>
			<? if ($n == ceil($count * (1 / 3)) || $n == ceil($count * (2 / 3))): ?>
				</td>
				<td style="vertical-align: top; white-space: nowrap;">
			<? endif ?>
			<input id="chk_type_<?= h($item["type"]) ?>" type="checkbox" name="child_types[]" value="<?= h($item["type"]) ?>"><label for="chk_type_<?= h($item["type"]) ?>"><?= h($item["type"]) ?> (<?= h($item["name"]) ?>)</label><br>
			<? $n++ ?>
		<? endforeach ?>
		</td>
	</tr>
</table>
<br>
<input type="submit" value="Сохранить">
</form>

</div>