<ul class="breadcrumb">
  <li>
    <a href="/manual">Manual</a> <span class="divider">/</span>
  </li>
  <li>
    <a href="/manual/classes">Classes</a> <span class="divider">/</span>
  </li>
  <li>
    <li class="active">Cookie</li>
  </li>
</ul>


<table class="table">
  <thead>	
  </thead>
  <tbody>
  
	<tr>				
		<td>	
		<pre class="prettyprint">Cookie::set_data($name, $value = null, $expire = 0, $path = "", $domain = "", $secure = false)</pre>		
		<p>
		Записывает массив (или произвольный объект) в куки.
		</p>
		</td>
	</tr>
	
	
	
	<tr>				
		<td>	
		<pre class="prettyprint">Cookie::get_data($name)</pre>		
		<p>
		Возвращает массив (или произвольный объект) из кук.
		</p>
		</td>
	</tr>

	
  </tbody>
</table>