    	
	<meta charset="utf-8">
	<title><?= h($_PAGE["title"]) ?></title>
	<meta name="description" content="<?= h($_PAGE["description"]) ?>" />
	<meta name="keywords" content="<?= h($_PAGE["keywords"]) ?>" />
	
	<?= $_PAGE["metas"] ?>
	
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
	<!-- Styles -->
	<link href="/bootstrap/css/bootstrap.css" rel="stylesheet">	
	<!-- link href="/bootstrap/css/bootstrap-responsive.css" rel="stylesheet"-->

	<link href="/css/layout.css?v=<?= $_REVISION ?>" rel="stylesheet">	
	<link href="/js/redactor/css/redactor.css" rel="stylesheet">	

	<!-- Le fav and touch icons -->
	<link rel="shortcut icon" href="/img/favicon.ico">
	<link rel="apple-touch-icon-precomposed" sizes="144x144" href="/bootstrap/img/apple-touch-icon-144-precomposed.png">
	<link rel="apple-touch-icon-precomposed" sizes="114x114" href="/bootstrap/img/apple-touch-icon-114-precomposed.png">
	<link rel="apple-touch-icon-precomposed" sizes="72x72" href="/bootstrap/img/apple-touch-icon-72-precomposed.png">
	<link rel="apple-touch-icon-precomposed" href="/bootstrap/img/apple-touch-icon-57-precomposed.png">
				
	<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
	<!--[if lt IE 9]>
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
		
	<!--[if lt IE 8]>
	<script src="/js/json2.js"></script>
	<![endif]-->