<ul class="breadcrumb">
  <li>
    <a href="/manual">Manual</a> <span class="divider">/</span>
  </li>
  <li>
    <a href="/manual/mvc">MVC</a> <span class="divider">/</span>
  </li>
  <li>
    <li class="active">Controller</li>
  </li>
</ul>

<table class="table">
  <thead>	
  </thead>
  <tbody>
    <tr>
		<td>	
		<p><strong>Установка рендера для страницы</strong></p>
		<pre class="prettyprint">render_view($view_name = null, $import_vars = array())</pre>
		<p>
		функция только устанавливает что рендерить - но не прекращает работу контроллера<br/>
		$view_name 	- название вьюхи<br/>
		$import_vars - массив данных для передачи во вьюху. Он НЕобязательный!<br/>
		Во вьюху автоматически попадают все переменные объвленные в контроллере.<br/>
		Но, иногда бывает нужно вывести текст без создания вьюхи, но в окружение лейаута.<br/><br/>
		Тогда можно написать хэлепер типа:<br/>
<pre class="prettyprint">
render_content($import_var){
  render_view('/helpers/content',array('content'=>$import_var));
}
</pre>	
		и сделать одну универсальную вьюху с любой переменной,
		а в нее соответственно прописать переменную &lt;?= $content ?&gt;
		
		</p>
		</td>		
	</tr>	
	<tr>				
		<td>	
		<p><strong>Удобно для AJAX-запросов</strong></p>
		<pre class="prettyprint">render_json($data)</pre>
		<p>
		На выход json_encode($data);exit;
		</p>		
		</td>
    </tr>
	
	<tr>				
		<td>	
		<p><strong>Редирект</strong></p>
		<p>
		Функция делает редирект на указанный адрес
		</p>
		<pre class="prettyprint">redirect_to($patch)</pre>
				
		</td>
    </tr>
	<tr>				
		<td>				
		<p><strong>Action</strong></p>
		<p>
		Получить или установить текущее действие
		</p>
		<pre class="prettyprint">action()</pre>
				
		</td>
    </tr>
	<tr>				
		<td>	
		<p><strong>Controller</strong></p>
		<p>
		Получить или установить текущее действие
		</p>
		<pre class="prettyprint">controller()</pre>
				
		</td>
    </tr>
	<tr>				
	<td>	
		<p><strong>Layout</strong></p>
		<p>
        Получить или установить текущий layout<br/>
		Если вызвано с одним аргументом - устанавливает указанный layout и возвращает его<br/>
		Если вызвано с двумя и второй аргумент true, то не устанавливает layout если он уже был установлен - возвращает текущий<br/>
		Если вызвано без аргументов просто возвращает текущий layout<br/>
		</p>
		<pre class="prettyprint">layout($name)</pre>
				
		</td>
    </tr>
	<tr>				
	<td>	
		<p><strong>Url</strong></p>
		<p>
	Функция выдаёт урл для страницы
	<br/>Вызов функции может быть разным.
	<br/>Если количество аргументов нечётное, то первый аргумент считается строкой УРЛ или её части если передано строковое значение,
	<br/>остальные аргументы беруться парами как ключ - значение, пример: url_for("http://www.example.com/images/test.jpg", "@host", "www.test.com")
	<br/>если же первый аргумент - массив, то он считается параметрами для составления урл, остальные аргументы игнорируются
	<br/>если же количество аргументов - чётное то они просто считаются парами ключ - значение
	<br/>Внимание: параметры имеющие значения null - не используются в формируемом УРЛ
	<br/>т.е. УРЛ формируется так как-будто бы вы эти параметры не передали
	<br/>Эту фичу очень удобно использовать совместно с параметром "@overwrite", передав значение какого-либо
	<br/>параметры как пустую как null - УРЛ сформируется на основе текущего контекста (с сохранением всех остальных параметров),
	<br/>а указанный параметр исчезнет
		</p>
		<pre class="prettyprint">url_for()</pre>
				
		</td>
    </tr>
	
  </tbody>
</table>