<div class="wtitle"><div><? if (action() == "roles-add"): ?>Создание роли<? else: ?>Редактирование роли<? endif ?></div></div>

<div style="padding: 2px;">

<form method="post">
<input type="hidden" name="do" value="save">

<fieldset>
	<legend>Общая информация</legend>
	<table>
		<tr>
			<td>Название:</td>
			<td><input type="text" name="name" style="width: 200px;"><err></td>
		</tr>
	</table>
</fieldset>

<fieldset>
	<legend>Доступ к типам объектов по-умолчанию (используется, если не указан специальный доступ ниже)</legend>
	<input type="checkbox" name="default_auth[]" value="<?= CMS_AUTH_READ ?>" id="chk_label_0"><label for="chk_label_0">Чтение</label>
	<input type="checkbox" name="default_auth[]" value="<?= CMS_AUTH_CREATE ?>" id="chk_label_1"><label for="chk_label_1">Создание</label>
	<input type="checkbox" name="default_auth[]" value="<?= CMS_AUTH_UPDATE ?>" id="chk_label_2"><label for="chk_label_2">Изменение</label>
	<input type="checkbox" name="default_auth[]" value="<?= CMS_AUTH_DELETE ?>" id="chk_label_3"><label for="chk_label_3">Удаление</label>
</fieldset>

<script type="text/javascript">
function clicked_on_type(type, is_checked)
{
	var o = $('type_auth_group_' + type);
	if (o) { o.style.display = is_checked ? 'inline-block' : 'none'; }
}	
</script>

<fieldset>
	<legend>Специальные доступы к типам объектов</legend>
	<table>
		<tr>
		<? $i = 0 ?>
		<? foreach ($types as $item): ?>
			<? if ($i && $i % 2 == 0): ?>
				</tr>
				<tr>
			<? endif ?>
			<td style="white-space: nowrap;">
				<div id="type_auth_group_<?= h($item["type"]) ?>" class="info-bg" style="border: 1px #888888 dashed; display: <?= $item["is_special_auth"] ? "inline-block" : "none" ?>;">
					<input type="checkbox" name="auth_types[<?= h($item["type"]) ?>][auth][]" value="<?= CMS_AUTH_READ ?>" id="chk_auth_<?= h($item["type"])?>_0"><label for="chk_auth_<?= h($item["type"])?>_0">Чтение</label>
					<input type="checkbox" name="auth_types[<?= h($item["type"]) ?>][auth][]" value="<?= CMS_AUTH_CREATE ?>" id="chk_auth_<?= h($item["type"])?>_1"><label for="chk_auth_<?= h($item["type"])?>_1">Создание</label>
					<input type="checkbox" name="auth_types[<?= h($item["type"]) ?>][auth][]" value="<?= CMS_AUTH_UPDATE ?>" id="chk_auth_<?= h($item["type"])?>_2"><label for="chk_auth_<?= h($item["type"])?>_2">Изменение</label>
					<input type="checkbox" name="auth_types[<?= h($item["type"]) ?>][auth][]" value="<?= CMS_AUTH_DELETE ?>" id="chk_auth_<?= h($item["type"])?>_3"><label for="chk_auth_<?= h($item["type"])?>_3">Удаление</label>
				</div>
				<input onclick="clicked_on_type('<?= j($item["type"]) ?>', this.checked);" id="chk_is_special_auth_<?= h($item["type"]) ?>" type="checkbox" name="auth_types[<?= h($item["type"]) ?>][is_special_auth]">
				<label for="chk_is_special_auth_<?= h($item["type"]) ?>"><?= h($item["name"]) ?> (<?= h($item["type"]) ?>)</label>
			</td>
			<? $i++ ?>
		<? endforeach ?>
		</tr>
	</table>
</fieldset>
<br>
<input type="submit" value="Сохранить">	
</form>

</div>