<script type="text/javascript" src="<?= CMS_PUBLIC_URI ?>/js/standard_list.js"></script>

<script type="text/javascript">
<!--
function check_all_buttons()
{
	var imgs = document.getElementsByTagName("IMG");
	var selected_count = get_object_length(selected_nodes);
	for (var i = 0; i < imgs.length; i++)
	{
		if (imgs[i].id && imgs[i].id.indexOf('button_') == 0)
		{
			imgs[i].className = 'tb_button_off';
			// здесь нужно писать условия при которых кнопки должны быть активны
			if (imgs[i].id == 'button_create') { continue; }
			if (imgs[i].id == 'button_edit' && selected_count == 1) { continue; }
			if (imgs[i].id == 'button_delete' && selected_count) { continue; }
			imgs[i].className = 'tb_button_disabled';
		}
	}
}

function tb_button_click(obj)
{
	if (obj.className != 'tb_button_disabled')
	{
		if (obj.id.indexOf('button_') == 0)
		{
			var command_name = obj.id.substr(7);
			switch (command_name)
			{
				case 'create':
					create_node();
					break;

				case 'edit':
					for (i in selected_nodes)
					{ edit_node(selected_nodes[i]); break; }
					break;

				case 'delete':
					if (confirm('Вы уверены что хотите удалить выбранных пользователей?'))
					{
						var params = [];
						for (i in selected_nodes) { params.push({'nodes[]': selected_nodes[i]}); }
						AJAX.run('<?= url_for("@overwrite", true, "action", "users-delete") ?>', params, 'POST');
					}
					break;

				default:
					alert('Unknown button: ' + command_name);
					break;
			}
		}
	}
}

function create_node() { location.href = '<?= url_for("@jsescape", true, "@escape", false, "action", "users-add") ?>'; }
function edit_node(id) { location.href = '<?= url_for("@jsescape", true, "@escape", false, "action", "users-edit") ?>?id=' + id; }
//-->
</script>

<div id="toolbar" style="position: absolute; left: 0px; top: 0px; width: 100%;">
	<table class="toolbarset"><tr><td>
		<table class="toolbar_group"><tr>
			<td class="tb_start"></td>
			<td><img class="tb_button_disabled" id="button_create" src="<?= CMS_PUBLIC_URI ?>/pics/create_document.gif" title="Добавить" onclick="tb_button_click(this);" onmouseover="tb_button_over(this);" onmouseout="tb_button_out(this);"></td>
			<td><img class="tb_button_disabled" id="button_edit" src="<?= CMS_PUBLIC_URI ?>/pics/edit_document.gif" title="Редактировать" onclick="tb_button_click(this);" onmouseover="tb_button_over(this);" onmouseout="tb_button_out(this);"></td>
			<td><img class="tb_button_disabled" id="button_delete" src="<?= CMS_PUBLIC_URI ?>/pics/delete.gif" title="Удалить" onclick="tb_button_click(this);" onmouseover="tb_button_over(this);" onmouseout="tb_button_out(this);"></td>
		</tr></table>
	</td></tr></table>
</div>
<div id="tree_area" style="position: absolute; left: 0px; top: 29px; width: 100%; overflow: auto;">
<? if (count($users)): ?>
	<table class="list">
	<tr>
		<? cms_list_header_field("login", "Логин") ?>
		<? cms_list_header_field("is_admin", "Администратор?") ?>
		<? cms_list_header_field(null, "Роли") ?>
	</tr>
	<? foreach ($users as $item): ?>
		<tr id="node_<?= h($item["id"]) ?>" onmouseup="clicked_on_node('<?= j($item["id"]) ?>', event);" ondblclick="double_clicked_on_node('<?= j($item["id"]) ?>');">
			<td><?= (!is_empty($item["login"]) ? h($item["login"]) : "&nbsp;") ?></td>
			<td><?= ($item["is_admin"]) ? "да" : "нет" ?></td>
			<td><?= (!is_empty($item["roles"]) ? h($item["roles"]) : "&nbsp;") ?></td>
		</tr>
	<? endforeach ?>
	</table>
<? else: ?>
	<table class="wide"><tr><td style="text-align: center;">
	<p class="graytext">[пусто]</p>
	</td></tr></table>
<? endif ?>
</div>

<script type="text/javascript">
<!--
function reposition_frames()
{
	try
	{
		$('tree_area').style.height = document.body.offsetHeight - $('toolbar').offsetHeight + 'px';
		$('tree_area').style.top = $('toolbar').offsetHeight + 'px';
	} catch (e) {}
}
add_event_listener(window, 'load', function() { setTimeout(function() { reposition_frames(); }, 10); });
add_event_listener(window, 'resize', function() { setTimeout(function() { reposition_frames(); }, 10); });
disable_selection($('toolbar'));
disable_selection($('tree_area'));
check_all_buttons();
//-->
</script>