<div class="wtitle"><div><? if (action() == "users-add"): ?>Создание пользователя<? else: ?>Редактирование пользователя<? endif ?></div></div>

<div style="padding: 2px;">

<form method="post">
<input type="hidden" name="do" value="save">

<table>
	<tr>
		<td>Логин:</td>
		<td><input type="text" name="login" style="width: 200px;"><err></td>
	</tr>
	<tr>
		<td>Пароль:</td>
		<td><input type="password" name="pass" style="width: 200px;"><err></td>
	</tr>
	<tr>
		<td>Пароль (ещё раз):</td>
		<td><input type="password" name="pass2" style="width: 200px;"><err></td>
	</tr>
	<tr>
		<td>Администратор:</td>
		<td><input type="checkbox" name="is_admin"><span class="graytext">(если установлено - будет доступен раздел "Администрирование")</span><err></td>
	</tr>
	<tr>
		<td></td>
		<td><b>Роли:</b></td>
	</tr>
	<tr>
		<td></td>
		<td>
			<? foreach ($roles as $item): ?>
				<input type="checkbox" name="roles[]" value="<?= h($item["id"]) ?>"><?= h($item["name"]) ?><br>
			<? endforeach ?>				
		</td>
	</tr>
</table>

<br>
<input type="submit" value="Сохранить">	
</form>

</div>