<script type="text/javascript">
<!--
function status_saved()
{
	with ($('status_message'))
	{ innerHTML = 'Данные успешно сохранены!'; className = 'success'; }
}

function status_wait()
{
	with ($('status_message'))
	{ innerHTML = 'Ждите...'; className = 'wait'; }
}

function status_clear()
{
	with ($('status_message'))
	{ innerHTML = ''; className = null; }
}

function submit_button_clicked()
{
	var node_form = parent.frames['frame_node_content'].document.getElementById('form_node');
	var buttons_form = $('form_buttons');
	if (node_form && buttons_form)
	{
		try
		{
			if (buttons_form.elements['chk_no_close'].checked) { node_form.elements['__cms__no_close'].value = 'yes'; }
			else { node_form.elements['__cms__no_close'].value = ''; }

			<? if ($is_multi_langs_save): ?>
				if (buttons_form.elements['chk_multi_save'].checked) { node_form.elements['__cms__save_all_langs'].value = 'yes'; }
				else { node_form.elements['__cms__save_all_langs'].value = ''; }
			<? endif ?>

			<? if (!isset($_GET["id"])): ?>
				if (buttons_form.elements['chk_one_more'].checked)
				{
					node_form.elements['__cms__one_more'].value = 'yes';
					if (buttons_form.elements['chk_no_clean'].checked) { node_form.elements['__cms__no_clean'].value = 'yes'; }
					else { node_form.elements['__cms__no_clean'].value = ''; }
				}
				else
				{
					node_form.elements['__cms__one_more'].value = '';
					node_form.elements['__cms__no_clean'].value = '';
				}
			<? endif ?>

			status_wait();
			parent.frames['frame_node_content'].$('form_node_submit_button').click();
		}
		catch (e) {}
	}
	else { parent.close(); }
}
//-->
</script>

<table class="wide"><tr><td>
	<form id="form_buttons" method="get">
	<table style="width: 100%;"><tr>
		<? if ($is_can_create || $is_can_update): ?>
			<td style="padding-left: 5px;"><input id="button_submit" type="button" onclick="submit_button_clicked();" value="Сохранить"></td>
		<? endif ?>
		<td style="padding-left: 5px; white-space: nowrap;"><input id="button_cancel" type="button" onclick="parent.close();" value="Отмена"></td>
		<? if ($is_can_create || $is_can_update): ?>
			<? if ($is_multi_langs_save): ?>
				<td style="padding-left: 5px; white-space: nowrap;"><span title="После нажатия кнопки &laquo;Сохранить&raquo; текущие данные будут скопированы на все языки"><input type="checkbox" id="lab_chk_multi_save" name="chk_multi_save" value="1"><label for="lab_chk_multi_save">Для всех языков</label></span></td>
			<? endif ?>
			<td style="padding-left: 5px; white-space: nowrap;"><span title="После нажатия кнопки &laquo;Сохранить&raquo; окно не закроется (переход в режим редактирования только что созданного объекта)"><input type="checkbox" id="lab_chk_no_close" name="chk_no_close" value="1"><label for="lab_chk_no_close">Не закрывать</label></span></td>
			<? if (!isset($_GET["id"])): ?>
				<td style="padding-left: 5px; white-space: nowrap;"><span title="После нажатия кнопки &laquo;Сохранить&raquo; окно не закроется, а перейдёт в режим добавления ещё одного объекта такого же типа"><input onclick="if (this.checked) { $('no_clean').style.display = ''; } else { $('no_clean').style.display = 'none'; }" type="checkbox" id="lab_chk_one_more" name="chk_one_more" value="1"><label for="lab_chk_one_more">Добавить ещё</label></span></td>
				<td style="display: <? if (@$_GET["chk_no_clean"]): ?>block<? else: ?>none<? endif ?>; padding-left: 5px; white-space: nowrap;" id="no_clean"><input type="checkbox" id="lab_chk_no_clean" name="chk_no_clean" value="1"><label for="lab_chk_no_clean">Не очищать поля</label></td>
			<? endif ?>
		<? endif ?>
		<td style="padding-left: 5px;">&nbsp;</td>
		<td style="padding-left: 10px; padding-right: 10px; white-space: nowrap;" id="status_message"></td>
		<td style="padding-right: 5px; width: 100%; text-align: right; white-space: nowrap;">
		<? if (isset($_GET["id"]) && $node !== false): ?>
			<? if ($prev_node_id): ?>
				<input type="button" value="&laquo; Назад" onclick="parent.load_node_edit_form('<?= hj($prev_node_id) ?>');">
			<? else: ?>
				<input type="button" value="&laquo; Назад" disabled>
			<? endif ?>
			<? if ($next_node_id): ?>
				<input type="button" value="Вперёд &raquo;" onclick="parent.load_node_edit_form('<?= hj($next_node_id) ?>');">
			<? else: ?>
				<input type="button" value="Вперёд &raquo;" disabled>
			<? endif ?>
		<? endif ?>
		</td>
	</tr></table>
	</form>
</td></tr>
</table>