<script type="text/javascript">
<!--
function status_saved()
{
	with ($('status_message'))
	{ innerHTML = 'Данные успешно сохранены!'; className = 'success'; }
}

function status_wait()
{
	with ($('status_message'))
	{ innerHTML = 'Ждите...'; className = 'wait'; }
}

function status_clear()
{
	with ($('status_message'))
	{ innerHTML = ''; className = null; }
}

function submit_button_clicked()
{
	var node_form = parent.frames['frame_node_content'].document.getElementById('form_node');
	var buttons_form = $('form_buttons');
	if (node_form && buttons_form)
	{
		try
		{
			if (buttons_form.elements['chk_no_close'].checked) { node_form.elements['__cms__no_close'].value = 'yes'; }
			else { node_form.elements['__cms__no_close'].value = ''; }

			<? if ($is_multi_langs_save): ?>
				if (buttons_form.elements['chk_multi_save'].checked) { node_form.elements['__cms__save_all_langs'].value = 'yes'; }
				else { node_form.elements['__cms__save_all_langs'].value = ''; }
			<? endif ?>

			status_wait();
			parent.frames['frame_node_content'].$('form_node_submit_button').click();
		}
		catch (e) {}
	}
	else { parent.close(); }
}
//-->
</script>

<table class="wide"><tr><td>
	<form id="form_buttons" method="get">
	<table><tr>
		<? if ($is_can_create || $is_can_update): ?>
			<td style="padding-left: 5px;"><input id="button_submit" type="button" onclick="submit_button_clicked();" value="Добавить"></td>
		<? endif ?>
		<td style="padding-left: 5px; white-space: nowrap;"><input id="button_cancel" type="button" onclick="parent.close();" value="Отмена"></td>
		<? if ($is_can_create || $is_can_update): ?>
			<? if ($is_multi_langs_save): ?>
				<td style="padding-left: 5px; white-space: nowrap;"><span title="После нажатия кнопки &laquo;Добавить&raquo; текущие данные будут добавлены для всех языков"><input type="checkbox" id="lab_chk_multi_save" name="chk_multi_save" value="1"><label for="lab_chk_multi_save">Для всех языков</label></span></td>
			<? endif ?>
			<td style="padding-left: 5px; white-space: nowrap;"><input type="checkbox" id="lab_chk_no_close" name="chk_no_close" value="1"><label for="lab_chk_no_close">Не закрывать</label></td>
		<? endif ?>
		<td style="padding-left: 5px;">&nbsp;</td>
		<td style="padding-left: 10px; padding-right: 10px; white-space: nowrap;" id="status_message"></td>
		<td style="width: 100%;">&nbsp;</td>
	</tr></table>
	</form>
</td></tr>
</table>