<div id="div_loader" style="position: absolute; top: 0px; left: 0px; width: 100%; height: 100%; z-index: 50;">
<iframe id="iframe_loader" style="width: 100%; height: 100%; border: 0px;" border="0" frameborder="0"></iframe>
</div>
<script type="text/javascript">
var frm = $('iframe_loader').contentWindow;
var html = '';
html += '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">';
html += '<html>';
html += '<head>';
html += '	<title></title>';
html += '	<link rel="stylesheet" type="text/css" href="<?= CMS_PUBLIC_URI ?>/css/cms.css">';
html += '</head>';
html += '<body class="threedface-bg"></body>';
html += '<table class="wide"><tr><td style="text-align: center;">Загрузка формы редактирования, ждите...</td></tr></table>';
html += '</html>';
frm.document.open();
frm.document.write(html);
frm.document.close();
</script>
