<?
// Если определена пользовательская функция генерации формы - запускаем её
// Первым параметром функция должна принимать строкове значение типа действия
// add - создание ноды, mod - модифицирование - рекомендуется использовать
// функции для генерации формы из form.helpers.php
if (function_exists("cms_show_node_form"))
{
	ob_start(); cms_show_node_form($_POST["__cms__do"]); $content = ob_get_clean();
	if (is_empty($content)) { standard_form(); } else { echo $content; }
}
else { standard_form(); }