<? include_block(CMS_PREFIX . "/node/form-loading") ?>

<script type="text/javascript">
function construct_list()
{
	<? if ($one2many_method == "linear"): ?>
		var selected_nodes = frames['frame_one2many'].frames['frame_list'].selected_nodes;
	<? elseif (is_empty($one2many_method) || $one2many_method == "catalog"): ?>
		var selected_nodes = frames['frame_one2many'].frames['frame_func'].selected_nodes;
		if (!get_object_length(selected_nodes)) { selected_nodes = frames['frame_one2many'].frames['frame_catalog'].selected_nodes; }
	<? endif ?>

	var form = document.getElementById('form_node');

	if (!get_object_length(selected_nodes))
	{
		parent.frames['frame_node_footer'].status_clear();
		alert('Выберите хотя бы один документ!');
		return false;
	}
	else
	{
		var elements = form.elements;
		for (var i = 0, c = elements.length; i < c; i++)
		{
			if (elements[i].name && elements[i].name == '__cms__selected_nodes[]')
			{
				form.removeChild(elements[i]);
				i = 0;
				c = elements.length;
			}
		}

		for (var i in selected_nodes)
		{
			var inp = document.createElement('INPUT');
			inp.type = 'hidden';
			inp.name = '__cms__selected_nodes[]';
			inp.value = selected_nodes[i];
			form.appendChild(inp);
		}
	}
	return true;
}
</script>

<form target="frame_node_processor" id="form_node" method="post" onsubmit="return construct_list();">
<input type="hidden" name="__cms__do" />
<input type="hidden" name="parent_id">
<input type="hidden" name="type">
<input type="hidden" name="__cms__no_close" value="">
<input type="hidden" name="__cms__save_all_langs" value="">
<input id="form_node_submit_button" type="submit" value="Сохранить" style="display: none;">
</form>
<?
if ($one2many_method == "linear")
{ $url = url_for("-controller", "list", "id", $one2many_parent_id, "only_type", $one2many_type, "lang", (isset($_POST["lang"]) ? $_POST["lang"] : null)); }
elseif (is_empty($one2many_method) || $one2many_method == "catalog")
{ $url = url_for("-controller", "catalog", "id", $one2many_parent_id, "only_type", $one2many_type, "lang", (isset($_POST["lang"]) ? $_POST["lang"] : null)); }
?>

<iframe name="frame_one2many" style="width: 100%; height: 100%;" frameborder="0" border="0" src="<?= $url ?>"></iframe>
<iframe name="frame_node_processor" src="<?= url_for(CMS_PUBLIC_URI . "/empty.php") ?>" frameborder="0" border="0" style="width: 0px; height: 0px; position: absolute; top: 0px; left: 0px; visibility: hidden;"></iframe>

<script type="text/javascript">
add_event_listener(window, 'load', function() { $('div_loader').style.display = 'none'; } );
</script>

