<div class="wtitle"><div><span>
<? if (isset($_GET["id"])): ?>
	<? if (!$is_can_read): ?>
		Недостаточно прав для чтения
	<? else: ?>
		Редактирование объекта "<?= h($type_name) ?>"
	<? endif ?>
<? elseif (!is_empty($type_name)): ?>
	Создание объекта "<?= h($type_name) ?>"
<? endif ?>
</span></div></div>
<script type="text/javascript">
<? if (isset($_GET["id"])): ?>
	<? if (!$is_can_read): ?>
		parent.document.title = 'Недостаточно прав для чтения';
	<? else: ?>
		parent.document.title = 'Редактирование объекта "<?= j($type_name) ?>"';
	<? endif ?>
<? elseif (!is_empty($type_name)): ?>
	parent.document.title = 'Создание объекта "<?= j($type_name) ?>"';
<? endif ?>
</script>
