<div id="toolbar" style="position: absolute; width: 100%; top: 0px; left: 0px;">
	<div class="wtitle"><div><span>&laquo;<?= h(get_name_by_system_name('root')) ?>&raquo;:</span> административный интерфейс</div></div>
	<table class="toolbarset"><tr><td>
		<? if (cms_is_have_auth_for_type("documents", CMS_AUTH_CREATE | CMS_AUTH_UPDATE | CMS_AUTH_DELETE)): ?>
			<table class="toolbar_group"><tr><td style="padding: 0px;"><div onclick="simple_button_press(function() { frames['frame_content'].location.href = '<?= url_for("-controller", "catalog") ?>'; }, this);" onmouseover="simple_button_over(this);" onmouseout="simple_button_out(this);" class="simple_button_off">Документы</div></td></tr></table>
		<? endif ?>
		<? foreach ($section_nodes as $item): ?>
			<? if ($item["is_catalog"]): ?>
				<table class="toolbar_group"><tr><td style="padding: 0px;"><div onclick="simple_button_press(function() { frames['frame_content'].location.href = '<?= url_for("-controller", "catalog", "id", $item["id"]) ?>'; }, this);" onmouseover="simple_button_over(this);" onmouseout="simple_button_out(this);" class="simple_button_off"><?= h($item["name"]) ?></div></td></tr></table>
			<? else: ?>
				<table class="toolbar_group"><tr><td style="padding: 0px;"><div onclick="simple_button_press(function() { frames['frame_content'].location.href = '<?= url_for("-controller", "list", "id", $item["id"]) ?>'; }, this);" onmouseover="simple_button_over(this);" onmouseout="simple_button_out(this);" class="simple_button_off"><?= h($item["name"]) ?></div></td></tr></table>
			<? endif ?>
		<? endforeach ?>
		<? if ($_AUTH["is_admin"]): ?>
			<table class="toolbar_group"><tr><td style="padding: 0px;"><div onclick="simple_button_press(function() { frames['frame_content'].location.href = '<?= url_for("-controller", "administration") ?>'; }, this);" onmouseover="simple_button_over(this);" onmouseout="simple_button_out(this);" class="simple_button_off">Администрирование</div></td></tr></table>
		<? endif ?>
		<? if (DEBUG_MODE): ?>
			<table class="toolbar_group"><tr><td style="padding: 0px;"><div onclick="simple_button_press(function() { frames['frame_content'].location.href = '<?= url_for("-controller", "debug") ?>'; }, this);" onmouseover="simple_button_over(this);" onmouseout="simple_button_out(this);" class="simple_button_off">DEBUG</div></td></tr></table>
		<? endif ?>
		<table class="toolbar_group"><tr><td style="padding: 0px;"><div onclick="if (confirm('Вы уверены?')) { location.href = '<?= url_for("action", "logout") ?>'; }" onmouseover="simple_button_over(this);" onmouseout="simple_button_out(this);" class="simple_button_off">Выйти</div></td></tr></table>
	</td></tr></table>
</div>
<iframe id="main_frame" name="frame_content" src="<?= CMS_PUBLIC_URI ?>/empty.php" frameborder="0" style="position: absolute; left: 0px; top: 0px; border: none; width: 100%;"></iframe>

<script type="text/javascript">
<!--
function reposition_frames()
{
	try
	{
		$('main_frame').style.height = document.body.offsetHeight - $('toolbar').offsetHeight + 'px';
		$('main_frame').style.top = $('toolbar').offsetHeight + 'px';
	} catch (e) {}
}
add_event_listener(window, 'load', function() { setTimeout(function() { reposition_frames(); }, 10); });
add_event_listener(window, 'resize', function() { setTimeout(function() { reposition_frames(); }, 10); });
disable_selection($('toolbar'));
//-->
</script>