<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<title>Административный интерфейс</title>
	<link rel="stylesheet" type="text/css" href="<?= CMS_PUBLIC_URI ?>/css/cms.css">
</head>
<body style="background-color: #e5e5e5;">
<table class="wide"><tr><td>
	<table style="margin-left: auto; margin-right: auto;">
		<tr>
			<td style="background-color: #dddddd;" colspan="3"><div style="height: 15px;"></div></td>
		</tr>
		<tr>
			<td style="background-color: #dddddd;"><div style="width: 3px;"></div></td>
			<td style="padding: 20px;">
				<script type="text/javascript">
				<!--
				document.write('<div style="padding-bottom: 15px; white-space: nowrap;"><b>&raquo; Для работы с интерфейсом требуется авторизация</b></div>');
				document.write('<form action="<?= url_for() ?>" method="post" style="margin: 0px;">');
				document.write('<table class="login">');
				document.write('	<tr><td style="text-align: right;">Логин:</td><td><input type="text" name="login" value="<?= h(@$_POST["login"]) ?>" style="width: 150px;"></td></tr>');
				<? if (!is_empty($error_string)): ?>
					document.write('	<tr><td></td><td style="padding-bottom: 5px; padding-top: 5px;"><?= j($error_string) ?></td></tr>');
				<? endif ?>
				document.write('	<tr><td style="text-align: right;">Пароль:</td><td><input type="password" name="password" style="width: 150px;"></td></tr>');
				document.write('	<tr><td></td><td><input type="submit" value="Авторизоваться"></td></tr>');
				document.write('</table>');
				document.write('</form>');
				//-->
				</script>
				<noscript>
					<p><span style="color: #ff0000; font-weight: bold;">У вас отключена поддержка JavaScript!</span></p>
					<p>Для работы с интерфейсом JavaScript должен быть включён, иначе работа будет не возможна.</p>
					<p>Данная настройка обычно находится в меню браузера "Настройки" - "Безопасность".</p>
				</noscript>
			</td>
			<td style="background-color: #dddddd;"><div style="width: 3px;"></div></td>
		</tr>
		<tr>
			<td style="background-color: #dddddd;" colspan="3"><div style="height: 15px;"></div></td>
		</tr>
	</table>
</td></tr></table>
</body>
</html>