<table class="wide"><tr><td>
<? if (!isset($_GET["create"])): ?>
	<form method="get" action="<?= url_for() ?>">
	<input type="hidden" name="create" value="1">
	<input type="hidden" name="random" value="<?= h(random()) ?>">
	<p style="text-align: center;"><b>Внимание!</b></p>
	<p style="text-align: center;">В базе данных не обнаружена главная системная таблица ЦМС. Возможно структура таблиц ещё не создана!</p>
	<p style="text-align: center;">Можно создать структуру таблиц прямо сейчас!</p>
	<p style="text-align: center;"><input type="submit" value="Создать структуру!"></p>
	</form>
<? else: ?>
	<? db_begin() ?>
	<p style="text-align: center;">
	<?
	$ddl_files = array
	(
		"system-functions" => CONTROLLERS_DIR . "/" . CMS_PREFIX . "/sql/system-functions.sql",
		"system-tables" => CONTROLLERS_DIR . "/" . CMS_PREFIX . "/sql/system-tables.sql",
	);
	foreach ($ddl_files as $name => $file): ?>
		<b>
		<? if ($name == "system-functions"): ?>Создание системных процедур:<? endif ?>
		<? if ($name == "system-tables"): ?>Создание системных таблиц:<? endif ?>
		</b>
		<? if ($name == "system-functions"): ?>
			<? $is_plpgsql_installed = db_select_cell("SELECT lanname FROM pg_language WHERE lanname = 'plpgsql'") ?>
			<? if (!$is_plpgsql_installed): ?>
				<span style="color: #ff0000">ОШИБКА:</span>
				Язык PL/pgSQL не обнаружен в вашей базе данных!<br>
				Требуется установить его с помощью команды <b>CREATE TRUSTED PROCEDURAL LANGUAGE plpgsql</b>
				<? break ?>
			<? endif ?>
		<? endif ?>
		<?
		$result = @db_query(db_raw(file_get_contents($file)));
		if ($result === false): ?>
			<span style="color: #ff0000">ОШИБКА: </span> <?= h(db_last_error(true)) ?><br>
			<? break ?>
		<? else: ?>
			Ok.<br>
		<? endif ?>
		<? if ($name == "system-functions"): ?>
			<? $is_plperl_installed = db_select_cell("SELECT lanname FROM pg_language WHERE lanname = 'plperl'") ?>
			<? $sql_script = null ?>
			<? if ($is_plperl_installed): ?>
				<b>Создание процедур на языке &laquo;PL/Perl&raquo;:</b>
				<? $sql_script = CONTROLLERS_DIR . "/" . CMS_PREFIX . "/sql/system-functions-plperl.sql" ?>
			<? else: ?>
				<b>Создание процедур на языке &laquo;PL/pgSQL&raquo;:</b>
				<? $sql_script = CONTROLLERS_DIR . "/" . CMS_PREFIX . "/sql/system-functions-plpgsql.sql" ?>
			<? endif ?>
			<?
			$result = @db_query(db_raw(file_get_contents($sql_script)));
			if ($result === false): ?>
				<span style="color: #ff0000">ОШИБКА: </span> <?= h(db_last_error(true)) ?><br>
				<? break ?>
			<? else: ?>
				Ok.<br>
			<? endif ?>
			<? if (!$is_plperl_installed): ?>
				<span style="color: #ff0000"><b>ВНИМАНИЕ!</b></span> Язык PL/Perl не обнаружен в вашей базе данных!<br>
				Рекомендуется установить его с помощью команды <b>CREATE TRUSTED PROCEDURAL LANGUAGE plperl</b><br>
				После установки выполните sql-скрипт расположенный в файле:<br>
				<?= h(CONTROLLERS_DIR . "/" . CMS_PREFIX . "/index/system-functions-plperl.sql") ?><br>
			<? endif ?>
		<? endif ?>
	<? endforeach ?>

	<? if (isset($result) && $result): ?>
		<b>Создание языка "Русский":</b>
		<? if (false === @db_insert("cms_languages", array("lang" => "ru", "name" => "Русский", "is_default" => true))): ?>
			<span style="color: #ff0000">ОШИБКА: </span> <?= h(db_last_error(true)) ?><br>
			<? $result = false ?>
		<? else: ?>
			Ok.<br>
			<? $result = true ?>
		<? endif ?>
	<? endif ?>

	<? if (isset($result) && $result): ?>
		<b>Создание языка "English":</b>
		<? if (false === @db_insert("cms_languages", array("lang" => "en", "name" => "English"))): ?>
			<span style="color: #ff0000">ОШИБКА: </span> <?= h(db_last_error(true)) ?><br>
			<? $result = false ?>
		<? else: ?>
			Ok.<br>
			<? $result = true ?>
		<? endif ?>
	<? endif ?>

	<? if (isset($result) && $result): ?>
		<?
		$standard_types = array
		(
			"documents" => array
			(
				"settings" => array
				(
					"name" => "Текстовая страница",
					"name_list" => "Текстовые страницы",
					"tree_name" => "{name}",
					"controller" => "text",
					"is_lang" => true
				),
				"fields" => array
				(
					array("name" => "Название", "field_name" => "name", "field_type" => "string", "is_req" => true),
					array("name" => "Текст", "field_name" => "full_text", "field_type" => "html")
				),
			),
			"params_groups" => array
			(
				"settings" => array
				(
					"name" => "Группа настроек",
					"name_list" => "Группы настроек",
					"tree_name" => "{name}",
					"is_lang" => true,
					"is_shared_fields_disabled" => true,
					"is_additional_tab_disabled" => true
				),
				"fields" => array
				(
					array("name" => "Название", "field_name" => "name", "field_type" => "string", "is_req" => true)
				),
			),
			"params" => array
			(
				"settings" => array
				(
					"name" => "Настройка",
					"name_list" => "Настройки",
					"tree_name" => "{name}",
					"icon" => "file.gif",
					"is_hidden_tree" => true,
					"is_lang" => true,
					"is_shared_fields_disabled" => true,
					"is_additional_tab_disabled" => true
				),
				"fields" => array
				(
					array("name" => "Название", "field_name" => "name", "field_type" => "string", "is_req" => true),
					array("name" => "Тип", "field_name" => "ptype", "field_type" => "integer", "is_req" => true, "is_idx" => true),
					array("name" => "Описание", "field_name" => "description", "field_type" => "plain_text"),
					array("name" => "Значение", "field_name" => "value", "field_type" => "plain_text")
				),
			),
			"string_constants" => array
			(
				"settings" => array
				(
					"name" => "Строковая константа",
					"name_list" => "Строковые константы",
					"tree_name" => "{name}",
					"icon" => "file.gif",
					"is_hidden_tree" => true,
					"is_lang" => true,
					"is_shared_fields_disabled" => true,
					"is_additional_tab_disabled" => true
				),
				"fields" => array
				(
					array("name" => "Идентификатор", "field_name" => "name", "field_type" => "string", "field_type_length" => 512, "is_req" => true, "is_uniq" => true, "is_idx" => true),
					array("name" => "Значение", "field_name" => "value", "field_type" => "plain_text")
				),
			),
		);
		?>
		<? foreach ($standard_types as $type => $data): ?>
			<b>Создание стандартного типа &laquo;<?= h($type) ?>&raquo;:</b>
			<?
			cms_catch_db_error();
			cms_create_type($type, $data["settings"]);
			foreach ($data["fields"] as $type_column) { cms_create_type_column($type, $type_column); }
			$result = cms_get_db_error();
			if ($result !== false): ?>
				<span style="color: #ff0000">ОШИБКА: </span> <?= h($result) ?><br>
				<? $result = false ?>
				<? break ?>
			<? else: ?>
				Ok.<br>
				<? $result = true ?>
			<? endif ?>
		<? endforeach ?>
	<? endif ?>

	<? if (isset($result) && $result): ?>
		<b>Создание отношений между стандартными типами:</b>
		<?
		cms_catch_db_error();
		db_insert("cms_node_type_childs", array("type" => "documents", "child_type" => "documents"));
		db_insert("cms_node_type_childs", array("type" => "params_groups", "child_type" => "params", "sibling_index" => 0));
		db_insert("cms_node_type_childs", array("type" => "params_groups", "child_type" => "params_groups", "sibling_index" => 1));
		$result = cms_get_db_error();
		if ($result !== false): ?>
			<span style="color: #ff0000">ОШИБКА: </span> <?= h($result) ?><br>
			<? $result = false ?>
		<? else: ?>
			Ok.<br>
			<? $result = true ?>
		<? endif ?>
	<? endif ?>

	<? if (isset($result) && $result): ?>
		<b>Внесение начальных данных:</b>
		<?
		cms_catch_db_error();

		cms_set_language("en");

		$root_id = set_node_data(array(
		"type" => "documents",
		"parent_id" => null,
		"system_name" => "root",
		"controller" => "index",
		"name" => "CMS",
		));

		$params_id = set_node_data(array(
		"type" => "documents",
		"parent_id" => $root_id,
		"system_name" => "params",
		"name" => "Settings",
		));

		$sc_id = set_node_data(array(
		"type" => "documents",
		"parent_id" => $root_id,
		"system_name" => "string_constants",
		"name" => "String constants",
		));

		$error404_id = set_node_data(array(
		"type" => "documents",
		"parent_id" => $root_id,
		"system_name" => "error404",
		"url_id" => "404",
		"controller" => "404",
		"name" => "404 - Not found",
		"full_text" => "<p>Page not found</p>",
		));

		db_insert("cms_node_childs", array("id" => $params_id, "child_type" => "params_groups"));
		db_insert("cms_node_childs", array("id" => $sc_id, "child_type" => "string_constants"));

		cms_set_language("ru");

		set_node_data(array("id" => $root_id, "name" => "CMS"));
		set_node_data(array("id" => $params_id, "name" => "Настройки"));
		set_node_data(array("id" => $sc_id, "name" => "Строковые константы"));
		set_node_data(array("id" => $error404_id, "name" => "404 - Не найдено", "full_text" => "<p>Такая страница не существует</p>"));

		$result = cms_get_db_error();
		?>
		<? if ($result !== false): ?>
			<span style="color: #ff0000">ОШИБКА!</span> <?= h($result) ?><br>
			<? $result = false ?>
		<? else: ?>
			Ok.<br>
			<? $result = true ?>
		<? endif ?>
	<? endif ?>
	</p>

	<? if (isset($result) && $result): ?>
		<p style="text-align: center;">Все таблицы успешно созданы!</p>
		<p style="text-align: center;">[<a href="<?= url_for("-controller", "index") ?>">Перейти к администрированию</a>]</p>
		<? db_commit() ?>
	<? endif ?>
<? endif ?>
</td></tr></table>