<script type="text/javascript">
<? A5::url_for_default("javascript") ?>
function status_saved()
{
	with ($('status_message'))
	{ innerHTML = 'Данные успешно перемещены!'; className = 'success'; }
}

function status_wait()
{
	with ($('status_message'))
	{ innerHTML = 'Ждите...'; className = 'wait'; }
}

function status_clear()
{
	with ($('status_message'))
	{ innerHTML = ''; className = null; }
}

function submit_button_clicked()
{
	try
	{
		var frame_catalog = parent.frames['frame_catalog'];
		var buttons_form = $('form_buttons');
		var frame_list = parent.opener.parent.frames['frame_list'];
	}
	catch (e) {}
	 
	if (frame_list && frame_catalog && buttons_form)
	{
		var len = get_object_length(frame_catalog.selected_nodes);
		if (!len) { alert('Выберите папку назначения!'); }
		else if (len > 1) { alert('Вы выбрали несколько папок, выберите одну!'); }
		else
		{
			status_wait();
			var params = [];
			
			for (var i in frame_catalog.selected_nodes) { params.push({'move_to': frame_catalog.selected_nodes[i]}); break; }
			for (var i in frame_list.selected_nodes) { params.push({'nodes[]': frame_list.selected_nodes[i]}); }
			
			AJAX.run('<?= url_for("action", "move-nodes") ?>', params, 'POST');
		}
	}
	else { parent.close(); }
}
<? A5::url_for_default("view") ?>
</script>

<table class="wide"><tr><td>
	<form id="form_buttons">
	<table><tr>
		<td style="padding-left: 5px;"><input id="button_submit" type="button" onclick="submit_button_clicked();" value="Начать перемещение"></td>
		<td style="padding-left: 5px; white-space: nowrap;"><input type="button" onclick="parent.close();" value="Отмена"></td>
		<td style="padding-left: 5px;">&nbsp;</td>
		<td style="padding-left: 10px; padding-right: 10px; white-space: nowrap;" id="status_message"></td>
		<td style="width: 100%;">&nbsp;</td>
	</tr></table>
	</form>
</td></tr>
</table>