<script type="text/javascript" src="<?= CMS_PUBLIC_URI ?>/js/standard_list.js"></script>

<script type="text/javascript">
<? A5::url_for_default("javascript") ?>
// Переопределяем массив выделенных строк, для того чтобы при загрузке страницы
// Была возможность восстановления выделения
var selected_nodes = parent.selected_nodes;

// Функция при загрузке страницы пробегаеться по всем выделенным нодам - проверяет
// Выделены-ли они - если нет - выделяет - если не смогла выделить - удаляет из списка выделенных
function restore_selected()
{
	for (var i in selected_nodes)
	{
		if (is_selected_node(selected_nodes[i]))
		{
			if (!do_node_selected(selected_nodes[i]))
			{ unselect_node(selected_nodes[i]); }
		}
	}
}

var list_parent_id = '<?= j($_GET["id"]) ?>';
var list_type = '<?= j($_GET["type"]) ?>';
var selection_enabled = false;
var saved_clicked_on_node = window.clicked_on_node;
var saved_double_clicked_on_node = window.double_clicked_on_node;
var dialog_wnd = null;

function get_node_name(id) { return document.getElementById('node_' + id).getAttribute('node_name', 2); }

function check_all_buttons()
{
	var selected_count = get_object_length(selected_nodes);
	var tagNames = ['IMG', 'DIV'];
	for (tagIndex in tagNames)
	{
		var tagName = tagNames[tagIndex];
		var objs = document.getElementsByTagName(tagName);
		for (var i = 0; i < objs.length; i++)
		{
			if (objs[i].id && objs[i].id.indexOf('button_') == 0)
			{
				objs[i].className = 'tb_button_off';
				// здесь нужно писать условия при которых кнопки должны быть активны
				<? if ($is_auth_type_create): ?>
					if (objs[i].id == 'button_create') { continue; }
					if (objs[i].id == 'button_copy' && selected_count) { continue; }
				<? endif ?>
				<? if ($is_auth_type_delete): ?>
					if (objs[i].id == 'button_delete' && selected_count) { continue; }
				<? endif ?>
				<? if ($is_auth_type_update): ?>
					if (objs[i].id == 'button_move' && selected_count) { continue; }
					if (objs[i].id == 'button_edit' && selected_count == 1) { continue; }
				<? endif ?>
				<? if ($is_auth_type_update && !isset($_GET["sort_cond"])): ?>
					if (objs[i].id == 'button_move_up' && selected_count) { continue; }
					if (objs[i].id == 'button_move_down' && selected_count) { continue; }
					if (objs[i].id == 'button_move_top' && selected_count) { continue; }
					if (objs[i].id == 'button_move_bottom' && selected_count) { continue; }
				<? endif ?>
				<? if ($is_auth_type_read && count($type_rows)): ?>
					if (objs[i].id == 'button_select') { continue; }
				<? endif ?>
				objs[i].className = 'tb_button_disabled';
			}
		}
	}
}

function tb_button_click(obj)
{
	if (obj.className != 'tb_button_disabled')
	{
		if (obj.id.indexOf('button_') == 0)
		{
			var command_name = obj.id.substr(7);
			switch (command_name)
			{
				case 'move_up':
				case 'move_down':
				case 'move_top':
				case 'move_bottom':
					var params = [];
					for (i in selected_nodes) { params.push({'nodes[]': selected_nodes[i]}); }

					if (command_name == "move_top" || command_name == "move_bottom")
					{ params.push({'do': 'full_move'}); }
					else if (command_name == "move_up" || command_name == "move_down")
					{ params.push({'do': 'one_move'}); }

					if (command_name == "move_top" || command_name == "move_up")
					{ params.push({'direction': 'up'}); }
					else if (command_name == "move_bottom" || command_name == "move_down")
					{ params.push({'direction': 'down'}); }

					AJAX.run('<?= url_for("@overwrite", true, "action", "type-nodes-move") ?>', params, 'POST');
					break;

				case 'create':
					create_node();
					break;

				case 'edit':
					for (i in selected_nodes)
					{ edit_node(selected_nodes[i]); break; }
					break;

				case 'copy':
					open_window('<?= url_for("action", "copy-frames") ?>', { 'width': 550, 'height': 500 });
					break;

				case 'move':
					open_window('<?= url_for("action", "move-frames") ?>', { 'width': 550, 'height': 500 });
					break;

				case 'delete':
					var len = get_object_length(selected_nodes);
					var do_delete = false;

					if (len > 1)
					{
						if (confirm('Вы уверены что хотите удалить выбранные документы?\nВыбрано документов: ' + len))
						{ do_delete = true; }
					}
					else
					{
						for (i in selected_nodes)
						{
							if (confirm('Вы уверены что хотите удалить "' + get_node_name(selected_nodes[i]) + '"?')) { do_delete = true; }
							break;
						}
					}

					if (do_delete)
					{
						var params = [];
						for (i in selected_nodes) { params.push({'nodes[]': selected_nodes[i]}); }
						AJAX.run('<?= url_for("@overwrite", true, "action", "type-nodes-delete") ?>', params, 'POST');
					}

					break;

				case 'select':
					if (selection_enabled)
					{
						disable_selection($('tree_area'));
						window.clicked_on_node = saved_clicked_on_node;
						window.double_clicked_on_node = saved_double_clicked_on_node;
						$('button_select').className = 'tb_button_on';
					}
					else
					{
						enable_selection($('tree_area'));
						unselect_all();
						$('button_select').className = 'tb_button_on border_black';
						window.clicked_on_node = function() { return true; }
						window.double_clicked_on_node = function() { return true; }
					}
					selection_enabled = selection_enabled ? false : true;
					break;

				default:
					alert('Unknown button: ' + command_name);
					break;
			}
		}
	}
}

function double_clicked_on_node(id)
{
	var params = { 'name': get_node_name(id), 'type': list_type };
	if (parent.callback_function) { parent.callback_function(id, params); }
	else if (parent.parent.callback_function) { parent.parent.callback_function(id, params); }
	else { edit_node(id); }
}

function create_node() { open_window('<?= url_for("-controller", "node", "parent_id", $_GET["id"], "type", $_GET["type"], "lang", isset($_GET["lang"]) ? $_GET["lang"] : null) ?>'); }
function edit_node(id)
{
	var url = append_url_param('<?= url_for("-controller", "node", "lang", isset($_GET["lang"]) ? $_GET["lang"] : null) ?>', 'id', id);
	open_window(url);
}

function reload_list() { location.href = '<?= url_for() ?>'; }
<? A5::url_for_default("view") ?>
</script>

<div id="header" style="position: absolute; left: 0px; top: 0px; width: 100%; z-index: 10;">
<div class="wtitle"><div><?= h($type_name_list) ?></div></div>
</div>

<div id="toolbar" style="position: absolute; left: 0px; top: 22px; width: 100%; z-index: 10;">
	<table class="toolbarset">
	<tr>
		<? if ($type_info["is_lang"] && $languages_count > 1): ?>
			<td style="padding-left: 2px;">Язык:</td>
			<td style="border-left: 0px;">
				<form method="post" action="<?= url_for() ?>">
				<select name="lang" onchange="this.form.submit();">
				<?
				$langs = db_select_all("
				SELECT
					lang,
					name
				FROM
					cms_languages
				ORDER BY
					is_default DESC,
					name
				");
				?>
				<? foreach ($langs as $item): ?>
					<option value="<?= h($item["lang"]) ?>" <? if (@$_GET["lang"] == $item["lang"]): ?>selected<? endif ?>><?= h($item["name"]) ?></option>
				<? endforeach ?>
				</select>
				</form>
			</td>
		<? endif ?>
		<td style="width: 100%;">
			<table class="toolbar_group"><tr>
				<td class="tb_start"></td>
				<td><div class="tb_button_disabled" id="button_create" onclick="tb_button_click(this);" onmouseover="tb_button_over(this);" onmouseout="tb_button_out(this);"><div><img src="<?= CMS_PUBLIC_URI ?>/pics/create_document.gif" style="float: left; width: 21px; height: 21px; border: 0px; margin-top: -4px;">Добавить</div></div></td>
				<td><div class="tb_button_disabled" id="button_edit" onclick="tb_button_click(this);" onmouseover="tb_button_over(this);" onmouseout="tb_button_out(this);"><div><img src="<?= CMS_PUBLIC_URI ?>/pics/edit_document.gif" style="float: left; width: 21px; height: 21px; border: 0px; margin-top: -4px;">Редактировать</div></div></td>
				<td><img class="tb_button_disabled" id="button_delete" src="<?= CMS_PUBLIC_URI ?>/pics/delete.gif" title="Удалить" onclick="tb_button_click(this);" onmouseover="tb_button_over(this);" onmouseout="tb_button_out(this);"></td>
			</tr></table>
			<table class="toolbar_group"><tr>
				<td class="tb_start"></td>
				<td><img class="tb_button_disabled" id="button_move_up" src="<?= CMS_PUBLIC_URI ?>/pics/move_up.gif" title="Сдвинуть вверх" onclick="tb_button_click(this);" onmouseover="tb_button_over(this);" onmouseout="tb_button_out(this);"></td>
				<td><img class="tb_button_disabled" id="button_move_down" src="<?= CMS_PUBLIC_URI ?>/pics/move_down.gif" title="Сдвинуть вниз" onclick="tb_button_click(this);" onmouseover="tb_button_over(this);" onmouseout="tb_button_out(this);"></td>
				<td class="tb_separator"></td>
				<td><img class="tb_button_disabled" id="button_move_top" src="<?= CMS_PUBLIC_URI ?>/pics/move_top.gif" title="Переместить в начало" onclick="tb_button_click(this);" onmouseover="tb_button_over(this);" onmouseout="tb_button_out(this);"></td>
				<td><img class="tb_button_disabled" id="button_move_bottom" src="<?= CMS_PUBLIC_URI ?>/pics/move_bottom.gif" title="Переместить в конец" onclick="tb_button_click(this);" onmouseover="tb_button_over(this);" onmouseout="tb_button_out(this);"></td>
			</tr></table>
			<table class="toolbar_group"><tr>
				<td class="tb_start"></td>
				<td><div class="tb_button_disabled" id="button_copy" onclick="tb_button_click(this);" onmouseover="tb_button_over(this);" onmouseout="tb_button_out(this);"><div><img src="<?= CMS_PUBLIC_URI ?>/pics/copy.gif" style="float: left; width: 21px; height: 21px; border: 0px; margin-top: -4px;">Копировать</div></div></td>
				<td><div class="tb_button_disabled" id="button_move" onclick="tb_button_click(this);" onmouseover="tb_button_over(this);" onmouseout="tb_button_out(this);"><div><img src="<?= CMS_PUBLIC_URI ?>/pics/move.gif" style="float: left; width: 21px; height: 21px; border: 0px; margin-top: -4px;">Переместить</div></div></td>
				<td class="tb_separator"></td>
				<td><div class="tb_button_disabled" id="button_select" title="Разрешает выделение данных таблицы мышкой" onclick="tb_button_click(this);" onmouseover="if (!selection_enabled) { tb_button_over(this); }" onmouseout="if (!selection_enabled) { tb_button_out(this); }"><div><img src="<?= CMS_PUBLIC_URI ?>/pics/selection.gif" style="float: left; width: 21px; height: 21px; border: 0px; margin-top: -4px;">Выделение</div></div></td>
			</tr></table>
		</td>
	</tr>
	</table>
</div>

<div id="tree_area" style="position: absolute; left: 0px; top: 51px; width: 100%; overflow: auto; z-index: 10;">
<? if (!$is_auth_type_read): ?>
	<table class="wide"><tr><td style="text-align: center;">
	<p class="graytext">[НЕДОСТАТОЧНО ПРАВ ДЛЯ ЧТЕНИЯ ДАННЫХ]</p>
	</td></tr></table>
<? elseif (count($type_rows)): ?>
	<table class="list">
	<tr>
		<? foreach ($final_field_list as $name => $info): ?>
			<? if ($name == "id" && !DEBUG_MODE) { $attr = array("style" => "display: none;"); } else { $attr = array(); } ?>
			<? cms_list_header_field($name, $info["name"], $attr) ?>
		<? endforeach ?>
	</tr>
	<? foreach ($type_rows as $item): ?>
		<tr id="node_<?= h($item["id"]) ?>" node_name="<?= h($node_names[$item["id"]]["name"]) ?>" onmouseup="clicked_on_node('<?= j($item["id"]) ?>', event);" ondblclick="double_clicked_on_node('<?= j($item["id"]) ?>');">
		<? foreach ($final_field_list as $field_name => $field_info): ?>
			<? $style = array("white-space" => "nowrap") ?>
			<? unset($content) ?>
			<? if ($field_name == "id" && !DEBUG_MODE) { $style["display"] = "none"; } ?>
			<? if (array_key_exists($field_name, $item)): ?>
				<? $field_value = $item[$field_name] ?>
				<? if ($field_info["type"] == "boolean"): ?>
					<? $style["text-align"] = "center" ?>
					<? $content = '<input type="checkbox" ' . ($field_value ? "checked" : null) . ' style="margin: -3px" onclick="this.checked = !this.checked">' ?>
				<? elseif (in_array($field_info["type"], array("file", "image", "flash"))): ?>
					<? $content = (!is_empty($field_value) ? h(basename($field_value)) . ' (' . human_size(PUBLIC_DIR . "/" . $field_value) . ') ' . '<a href="' . url_for("-controller", "main", "action", "download", "path", $field_value) . '" target="_blank" title="Скачать"><img src="' . CMS_PUBLIC_URI . '/pics/download.gif" style="width: 16px; height: 16px; border: 0px; vertical-align: -3px"></a>' : "&nbsp;") ?>
				<? else: ?>
					<?
					if (in_array($field_info["type"], array("integer", "filesize", "number", "sum", "price", "cost"))) { $style["text-align"] = "right;"; }
					elseif (in_array($field_info["type"], array("date", "time", "datetime", "age", "gender", "cost"))) { $style["text-align"] = "center;"; }
					?>
				<? endif ?>
			<? else: ?>
				<? $content = "<b>" . h("<UNKNOWN>") . "</b>"; ?>
			<? endif ?>
			<? array_walk($style, function(&$v, $k) { $v = $k . ": " . $v; }) ?>
			<? if (!isset($content)) { $content = (!is_empty($field_value) ? h(cms_format_by_type($field_value, $field_info["type"])) : "&nbsp;"); } ?>
			<td<? if ($style): ?> style="<?= implode(";", $style) ?>"<? endif ?>><?= $content ?></td>
		<? endforeach ?>
		</tr>
	<? endforeach ?>
	</table>
<? else: ?>
	<table class="wide"><tr><td style="text-align: center;">
	<p class="graytext">[пусто]</p>
	</td></tr></table>
<? endif ?>
</div>

<div id="page_navigation" style="position: absolute; left: 0px; top: 0px; width: 100%; z-index: 10;">
	<? if ($is_auth_type_read): ?>
		<table style="width: 100%;">
		<tr>
			<td class="threedface-bg" style="white-space: nowrap; padding-right: 5px;">Всего записей: <?= h($type_rows_count) ?></td>
			<td class="threedface-bg" style="width: 100%;">
			<? if ($page_nav["pages"]): ?>
				<table style="float: left;"><tr><td><div onclick="simple_button_press(function() { location.href = '<?= url_for("@overwrite", true, $page_nav["varname"], -1) ?>'; }, this);" onmouseover="simple_button_over(this);" onmouseout="simple_button_out(this);" class="simple_button_<? if ($is_list_all_type_nodes): ?>on<? else: ?>off<? endif ?>">ВСЕ</div></td></tr></table>
			<? endif ?>
			<? if ($page_nav["prev_section"]): ?>
				<table style="float: left;"><tr><td><div onclick="simple_button_press(function() { location.href = '<?= url_for("@overwrite", true, $page_nav["varname"], $page_nav["first_page"]["number"]) ?>'; }, this);" onmouseover="simple_button_over(this);" onmouseout="simple_button_out(this);" class="simple_button_off"><?= ($page_nav["first_page"]["number"] - 1) * $page_nav["limit"] + 1 ?>-<?= ($page_nav["first_page"]["number"] - 1) * $page_nav["limit"] + $page_nav["limit"] ?></div></td></tr></table>
				<table style="float: left;"><tr><td><div onclick="simple_button_press(function() { location.href = '<?= url_for("@overwrite", true, $page_nav["varname"], $page_nav["prev_section"]["number"]) ?>'; }, this);" onmouseover="simple_button_over(this);" onmouseout="simple_button_out(this);" class="simple_button_off">...</div></td></tr></table>
			<? endif ?>
			<? if ($page_nav["pages"]): ?>
				<? foreach ($page_nav["pages"] as $page): ?>
					<table style="float: left;"><tr><td><div onclick="simple_button_press(function() { location.href = '<?= url_for("@overwrite", true, $page_nav["varname"], $page["number"]) ?>'; }, this);" onmouseover="simple_button_over(this);" onmouseout="simple_button_out(this);" class="simple_button_<? if ($page["current"] && !$is_list_all_type_nodes): ?>on<? else: ?>off<? endif ?>"><?= ($page["number"] - 1) * $page_nav["limit"] + 1 ?>-<?= ($page["number"] - 1) * $page_nav["limit"] + $page_nav["limit"] ?></div></td></tr></table>
				<? endforeach ?>
			<? endif ?>
			<? if ($page_nav["next_section"]): ?>
				<table style="float: left;"><tr><td><div onclick="simple_button_press(function() { location.href = '<?= url_for("@overwrite", true, $page_nav["varname"], $page_nav["next_section"]["number"]) ?>'; }, this);" onmouseover="simple_button_over(this);" onmouseout="simple_button_out(this);" class="simple_button_off">...</div></td></tr></table>
				<table style="float: left;"><tr><td><div onclick="simple_button_press(function() { location.href = '<?= url_for("@overwrite", true, $page_nav["varname"], $page_nav["last_page"]["number"]) ?>'; }, this);" onmouseover="simple_button_over(this);" onmouseout="simple_button_out(this);" class="simple_button_off"><?= ($page_nav["last_page"]["number"] - 1) * $page_nav["limit"] + 1 ?>-<?= ($page_nav["last_page"]["number"] - 1) * $page_nav["limit"] + $page_nav["limit"] ?></div></td></tr></table>
			<? endif ?>
			</td>
		</tr>
		</table>
	<? endif ?>
</div>

<script type="text/javascript">
<!--
function reposition_frames()
{
	var header = $('header');
	var toolbar = $('toolbar');
	var tree_area = $('tree_area');
	var page_navigation = $('page_navigation');
	try
	{
		tree_area.style.height = document.body.offsetHeight - header.offsetHeight - toolbar.offsetHeight - page_navigation.offsetHeight + 'px';
		tree_area.style.top = header.offsetHeight + toolbar.offsetHeight + 'px';
		toolbar.style.top = header.offsetHeight + 'px';
		page_navigation.style.top = header.offsetHeight + toolbar.offsetHeight + tree_area.offsetHeight + 'px';
	} catch (e) {}
}
add_event_listener(window, 'load', function() { setTimeout(function() { reposition_frames(); }, 10); });
add_event_listener(window, 'resize', function() { setTimeout(function() { reposition_frames(); }, 10); });
disable_selection($('header'));
disable_selection($('toolbar'));
disable_selection($('tree_area'));
disable_selection($('page_navigation'));
restore_selected();
check_all_buttons();
//-->
</script>