<? if (!is_empty($error_message)): ?>
	alert('<?= j($error_message) ?>');
<? else: ?>
	var nodes = [];
	var load_node_childs = [];
	<? foreach ($affected_nodes as $item_id): ?>
		nodes.push('<?= h($item_id) ?>');
		load_node_childs.push('<?= h($item_id) ?>');
	<? endforeach ?>
	var catalog_frame = null;
	try { catalog_frame = parent.parent.frames['frame_catalog']; } catch (e) {}
	if (catalog_frame) { catalog_frame.expand_tree(nodes, { 'load_node_childs': load_node_childs, 'node_inclusive': true }); }
	reload_list();
<? endif ?>