<?/* Powered by twitter bootstrap [ http://twitter.github.com/bootstrap/ ] */?>
<!DOCTYPE html>
<html lang="ru"> 
<head>
<? include_block("_metas") ?>
<? include_block("_css") ?>
<? include_block('_js')?>
</head>
<body>
	<div class="container">
	
		<!--Header-->		
			<? include_block("/partials/header") ?>	
		<!--/Header-->
		
		<!--Body-->
		<div class="row-fluid">
			<div class="span3">
				<!-- Sidebar left -->
					<? include_block("/partials/left_sidebar") ?>
				<!-- /Sidebar left -->
			</div>
			<div class="span9">
				<!-- Content -->
					<? include_view() ?>
				<!-- /Content -->
			</div>
		</div>
		<!--/Body-->
		
		<!--Footer-->
			<? include_block("/partials/footer") ?>
		<!--/Footer-->	
		
	</div>
	
	<!-- Popups -->	
		<? include_block("_popups") ?>	
	<!-- /Popups -->	
	
	<!-- Counters -->	
		<? include_block('_analytics')?>
	<!-- /Counters -->	
</body>
</html>

