<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Manual</title>
	
	<!-- Le fav and touch icons -->
	<link rel="shortcut icon" href="/img/favicon.ico">
	<link rel="apple-touch-icon-precomposed" sizes="144x144" href="/bootstrap/img/apple-touch-icon-144-precomposed.png">
	<link rel="apple-touch-icon-precomposed" sizes="114x114" href="/bootstrap/img/apple-touch-icon-114-precomposed.png">
	<link rel="apple-touch-icon-precomposed" sizes="72x72" href="/bootstrap/img/apple-touch-icon-72-precomposed.png">
	<link rel="apple-touch-icon-precomposed" href="/bootstrap/img/apple-touch-icon-57-precomposed.png">
	
	
    <!-- Le styles -->
    <link href="/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- <link href="/admin/css/bootstrap-responsive.min.css" rel="stylesheet"> -->
    
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="/bootstrap/js/bootstrap.min.js"></script>
	
	<link href="/manual/css/prettify.css" type="text/css" rel="stylesheet" />	
	<script type="text/javascript" src="/manual/js/prettify.js"></script>
	
	<style type="text/css">
	
		table th.title {background-color:gainsboro}

		/*
		pre.prettyprint {border:none !important}
		pre{border:none !important}
		*/

	</style>

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
	
	<script type="text/javascript">
	
		var A5 = {
			controller 	: '<?= controller(); ?>',
			action 		: '<?= action(); ?>',
			debug		: '<?= DEBUG_MODE; ?>',
			cookie		: <?= json_encode($_COOKIE); ?>,
		}
		
	</script>
  </head>
  <body onload="prettyPrint()">
    <div class="container">
        <div style="height: 5px;"></div>
		<div class="navbar">
		  <div class="navbar-inner">
		    <div class="container">
                <a class="brand" href="/manual">Manual</a>
				<ul class="nav">
				  <li><a href="/manual/mvc">MVC</a></li>
				  <li><a href="/manual/classes">Classes</a></li>
				  <li><a href="/manual/helpers">Helpers</a></li>
				  <li><a target="_blank" href="http://twitter.github.com/bootstrap/">Twitter bootstrap</a></li>		
				</ul>				
		    </div>
		  </div>
		</div>  
		
		<? include_view() ?>
		
    </div>
  </body>
</html>
